# Generated by Django 4.2.5 on 2023-10-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='subcategoria_id',
            new_name='subcategoria',
        ),
    ]
